#!groovy

/*
  This file is the entry point for the creation of a cluster and simply takes
  care of setting up the correct workspace and then delegate to cluster_builder.groovy
  the actual creation
*/

node {
  currentBuild.displayName = "TEST_${currentBuild.number}"
  currentBuild.description = "[Testing] Branch: test"
  
  sh 'env > env.txt'
  
  try {
      env.BUILD_WORKSPACE = pwd()
      
      BUILDER_DIR = "${BUILD_WORKSPACE}@script/scripts/builder"

      def builder = load "${BUILDER_DIR}/builder.groovy"
      builder.buildAgent()
  } catch (e) {
      currentBuild.result = 'FAILURE'
      throw e
  }
}
